apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      nodePort: 30036
  selector:
    app: hello-world
  type: NodePort